# Generated by Django 4.2.4 on 2023-08-13 01:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_alter_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likers",
            field=models.ManyToManyField(
                blank=True,
                related_name="people_who_have_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 13, 1, 29, 0, 440590, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
