# Generated by Django 4.2.4 on 2023-08-13 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_post_likers_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 13, 5, 39, 31, 741873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
