# Generated by Django 4.2.4 on 2023-08-13 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to="network.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 13, 5, 39, 43, 165560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
