# Generated by Django 4.2.4 on 2023-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_user_posts_alter_post_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likers",
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
