# Generated by Django 4.2.4 on 2023-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_remove_post_likers_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
